# .github/workflows/deploy.yml
# Deploy a Vite React project to GitHub Pages and generate image descriptions

name: Deploy Vite React App to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:
    inputs:
      regenerate_descriptions:
        description: 'Regenerate image descriptions'
        required: false
        default: 'false'

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # or the version you are using

      - name: Install dependencies
        run: npm install

      - name: Generate image descriptions
        if: ${{ github.event.inputs.regenerate_descriptions == 'true' || github.event_name != 'workflow_dispatch' }}
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: node generate_descriptions.js

      - name: Build Vite project
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./dist  # Vite output directory

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
